version: '3.7'      
services:
  dbpostgresql:
    container_name: dbpostgresql_v1    
    image: "postgres:9.6"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql      
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "em_learning_db"      
    networks:
      - dbpostgresql-network-v1

networks:
  dbpostgresql-network-v1:
    external: true